### ISSUE TITLE
Color mismatches compared to upstream palette

### ISSUE THREAD

**Issue by antoineco** [ewal/kitty-everforest#3]
While looking into the collection of [upstream color themes for Kitty](https://github.com/kovidgoyal/kitty-themes/tree/master/themes), I noticed that somebody had already contributed variations of the Everforest color scheme. So first of all, thanks a lot for this! 🙌 

I noticed that a few of the 16 base colors were misused though. Here are a few examples, illustrated in the screenshot(s) below:

- **`black` and `foreground` are the same.**

   _Problem_: This should never be the case in a terminal color scheme, because it can render some text invisible.

   _Fix_: strictly stick to the `fg` color defined in the scheme's [palette2](https://github.com/sainnhe/everforest/blob/3883583eb32776203e52afaa421b1a590b689ede/autoload/everforest.vim#L124-L140), which is for _foreground_ colors. You may also notice that `palette2` remains the same in all hard, medium and soft variations of the scheme.

- **in the dark theme, base colors are bright, bright colors are not**

   _Problem_: These are semantically reversed. A bright color shouldn't be darker than its non-bright counterpart.

   _Fix_: see next point

- **Foreground colors are arbitrarily selected from either the dark or light palette**

   _Problem_: Probably my biggest concern with the current version of this Kitty theme. After inspecting the different colors, I realized that they have been selected arbitrarily from both the dark and light variants of the scheme's [palette2](https://github.com/sainnhe/everforest/blob/3883583eb32776203e52afaa421b1a590b689ede/autoload/everforest.vim#L124-L140), which explains the previous point. In the original color scheme, colors from each variant are strictly defined in palette1 + palette2. The dark variant doesn't "borrow" colors from the light variant, and vice versa. This makes this theme a custom interpretation of Everforest, but not a strict port of the original Vim Everforest colors.

   _Fix_: only use colors from the "dark" palette1 + palette2 in the dark themes, only use colors from the "light" palette1 + palette2 in the light theme.

I have "fixed" versions of all 6 variants locally, but before submitting a PR I wanted to share the result with you, and ask whether you would be willing to accept those changes.

_before_

![before](https://user-images.githubusercontent.com/3299086/182625293-0667753c-e03a-47d8-932f-7e1340938689.png)
![before](https://user-images.githubusercontent.com/3299086/182644038-229393fd-971c-449a-9962-94ab68fe485e.png)

_after_

![after](https://user-images.githubusercontent.com/3299086/182651946-adf8bc5e-eab5-460f-9811-4dead18e5132.png)
![after](https://user-images.githubusercontent.com/3299086/182643889-cd7603ff-70d9-49bc-b0a6-dfd680963d30.png)

**Comment by ewal** [comment]
Very nice! Please go ahead and submit the pr :+1: :tada:

**Comment by ewal** [comment]
@antoineco, thanks again for your contribution, truly appreciated. There are however one thing with the fixed color palette that I believe degrades the end user experience.

With the applied fixes some labels becomes hard to read. I took the liberty to adjust certain colors when I made the themes as seen in the screen shots below, specifically the color used for the git branch label so the contrast would be more profound. I'd prefer to use the strict colors everywhere but it isn't as friendly for the eyes. What's your take on this?

Previously:
<img width="421" alt="old" src="https://user-images.githubusercontent.com/676873/183256749-a9d11590-ef8e-4ed1-83ab-a65c2a11102f.png">


Updated:
![image](https://user-images.githubusercontent.com/676873/183256736-ae4959a3-cb60-40bc-afc4-e703bf0e239a.png)

**Comment by antoineco** [comment]
Interesting point.

It seems like you're using the `pure` prompt for Zsh? By default, Pure uses the [color 242](https://github.com/sindresorhus/pure/blob/2d89ef1d06f76997790b45df5ac447f0c3ffd34c/pure.zsh#L816) for the [`git:branch` component](https://github.com/sindresorhus/pure#colors).

On both of the machines I use (macOS with Kitty, Windows 11 with Windows Terminal), the Pure prompt looks like this with the colors submitted in my previous PR:

![image](https://user-images.githubusercontent.com/3299086/183257382-92638106-98e0-4013-9425-b40a6bb10271.png)

**Questions**

- Is your Pure prompt maybe configured to use `black` (or `0`) instead of `242`?

   If that is the case, in any given dark terminal theme I would expect `#black` on `#background` to look _very_ dark. Likewise, in a light terminal theme, `#brightwhite` on `#background` will look very light (the other extreme of the color range).

   Take the example of the popular [Nord theme](https://raw.githubusercontent.com/arcticicestudio/nord-alacritty/develop/assets/scrot-hero.png), or even this [huge list of terminal themes](https://github.com/eendroroy/alacritty-theme#color-schemes); the color `black` (30m) looks always very dark on the background, which is usually considered to be expected because terminal applications don't explicitly use `#black` as foreground color. They use either `#foreground`, one of the 16 ANSI colors except white/black, or a well-chosen color in the 256 color range. Which is why I would be surprised if your shell prompt was defaulting to `black` / `0`.

- If not, could it be that something is overriding your terminal colors? I know that Kitty allows redefining all 256 terminal colors.

   I usually use the script from the following Gist to display my 256 colors:

   ```sh
    curl -s https://gist.githubusercontent.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263/raw/e50a28ec54188d2413518788de6c6367ffcea4f7/print256colours.sh | bash
    ```

   I get this as output (pay attention to the grays at the end especially):

   ![image](https://user-images.githubusercontent.com/3299086/183258262-4a405018-4355-4d49-88e5-699342b7bd40.png)

**Comment by ewal** [comment]
Nice catch and I believe you're right about Pure. I'm currently using Fish shell with Pure in Linux and on Mac. I'll investigate this further.

**Comment by ewal** [comment]
This is the output I got from the script you provided:

![image](https://user-images.githubusercontent.com/676873/183259603-f1b1e8c3-d11d-4861-ba4d-12c46bf988db.png)

**Comment by antoineco** [comment]
Ah, the Fish port of Pure uses `#brightblack` as foreground color for the Git branch: https://github.com/pure-fish/pure/blob/2d07e74567e9190c82ae66c37c34ca86850cd9ac/conf.d/pure.fish#L6

I tried applying the same color in (Zsh) Pure, and you're right. I think the current `#brightblack` looks OK for autocomplete suggestions, but it's too dark for prompt components (see screenshot below for a comparison of `242` vs. `#black` vs. `#brightblack`):

![image](https://user-images.githubusercontent.com/3299086/183259941-2b278052-28e0-4e60-a57a-bbff696e4552.png) 

I still believe a shell prompt should use better colors than `#(bright)white` or `#(bright)black` as foreground color to display information — unless it was specifically designed for either a dark or light theme — but I also agree that a better contrast could be a sensible default.

**Comment by ewal** [comment]
I learnt something new today, thank you :beers: 
I fixed my shell theme by modifying a couple of Pure vars. Lesson learnt from this is to run a non modified terminal if ever creating another theme again :slightly_smiling_face:
